### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Douglaskav** [Douglaskav/Lumero#2]
# To-do

### Design
- [x] Brainstorm
- [x] Briefing
- [x] Wireframe
- [x] Construção das telas

#### Codificação das Telas
- [x] Onboarding
- [x] BookProfile
- [x] BookReader
- [x] BookPlayer
- [x] Explore
- [x] Favorites
- [x] Home
- [x] Sign In
- [x] Sign Up
- [x] Profile
---
- [x] Salvar token com AsyncStorage
- [x] Verificação de authorização em rotas
- [x] Separar Rotas por Context
### Integração com api em
?
---
- [x] Shimmer Effect
- [x] Controle de playlist
- [x] Puxar livros favoritos do usuário
- [x] Automaticamente passar para o proximo audio quando acabar
- [x] Puxar reviews referente a cada livro

### Backend
- [x] Criação de rotas
- [x] Crição de controllers e services
- [x] Cadastro de usuários
- [x] Cadastro de livros
- [x] Cadastro de reviews
- [x] Comunicação entre chaves no banco de dados
- [x] Testes de Integração
- [x] Upload de imagens
- [x] Inserir os livros no banco de dados
- [x] Rota para salvar livros favoritos do usuários
